#!/usr/bin/env python3
"""Bundle index.html + styles.css + script.js into a single preview.html.

The preview file is fully self-contained (one double-clickable file), so it can
be emailed, dropped on a desktop, or opened straight from the file system.
Run after editing any source file:

    python3 build-preview.py
"""

from pathlib import Path

HERE = Path(__file__).parent

html = (HERE / "index.html").read_text(encoding="utf-8")
css = (HERE / "styles.css").read_text(encoding="utf-8")
js = (HERE / "script.js").read_text(encoding="utf-8")

html = html.replace(
    '<link rel="stylesheet" href="styles.css" />',
    "<style>\n" + css + "\n</style>",
)
html = html.replace(
    '<script src="script.js"></script>',
    "<script>\n" + js + "\n</script>",
)
html = html.replace(
    "<title>",
    "<!-- Generated by build-preview.py — do not edit directly. -->\n<title>",
    1,
)

out = HERE / "preview.html"
out.write_text(html, encoding="utf-8")
print(f"Wrote {out} ({out.stat().st_size / 1024:.1f} KB)")
